### ISSUE TITLE
Chat APIでタスクの担当者変更エンポイントがありますか。

### ISSUE THREAD

**Issue by chungth** [chatwork/api#18]
Chatworkの担当様へ

お世話になります。
ハポソフトのチュンです。

弊社のチームは現在ChatworkAPIを使ったシステムを開発しております。
弊社のシステムでChatworkのタスクと連動したいですが、ChatworkAPIでタスクの担当者を変更する方法がありますか。
Chatwork Apiのドキュメントで探しましたが、担当者変更エンんポイントが見つけませんでした。
http://developer.chatwork.com/ja/endpoint_rooms.html#PUT-rooms-room_id-tasks-task_id-status

もしそのエンポイントが公開されているであれば、ご教示していただけないでしょうか。

よろしくお願いします。

**Comment by hayasshi** [comment]
@chungth 

こちら何も対応できておらず、大変申し訳ありませんでした。
Chatwork API のご利用ありがとうございます。

もしかしたら、すでに必要ない情報かもしれませんが、回答いたします。

> ChatworkAPIでタスクの担当者を変更する方法

こちらですが、目的に合致したものはございません。

方法としては、下記の方法となってしまいます。

1. [タスクステータス変更のエンドポイント](https://developer.chatwork.com/reference/put-rooms-room_id-tasks-task_id-status)をつかって、該当のタスクを完了していただき、
2. 新しい担当者を設定して[新しくタスクを作成](https://developer.chatwork.com/reference/post-rooms-room_id-tasks)していただく

以上になります。

重ね重ねになりますが、この度は回答に大変時間がかかり申し訳ございません。
このリポジトリの issue や Pull request に対する運用体制、方針のほうの検討と今後の取り扱いを定めているところですので、ご容赦いただけますと幸いです。

引き続きよろしくおねがいします。
